### ISSUE TITLE
ValueError: mmap length is greater than file size

### ISSUE THREAD

**Issue by diabolianka** [wikipedia2vec/wikipedia2vec#10]
attempting basic usage:
```
/usr/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/usr/lib/python3.5/contextlib.py:59: UserWarning: mmap_mode "c" is not compatible with compressed file /mnt/big_data/enwiki_20180420_100d.pkl.bz2. "c" flag will be ignored.
  return next(self.gen)
Traceback (most recent call last):
  File "words.py", line 3, in <module>
    wiki2vec = Wikipedia2Vec.load('/mnt/big_data/enwiki_20180420_100d.pkl.bz2')
  File "wikipedia2vec/wikipedia2vec.pyx", line 157, in wikipedia2vec.wikipedia2vec.Wikipedia2Vec.load
  File "/home/.local/lib/python3.5/site-packages/joblib/numpy_pickle.py", line 596, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/home/.local/lib/python3.5/site-packages/joblib/numpy_pickle.py", line 524, in _unpickle
    obj = unpickler.load()
  File "/usr/lib/python3.5/pickle.py", line 1039, in load
    dispatch[key[0]](self)
  File "/home/.local/lib/python3.5/site-packages/joblib/numpy_pickle.py", line 352, in load_build
    self.stack.append(array_wrapper.read(self))
  File "/home/.local/lib/python3.5/site-packages/joblib/numpy_pickle.py", line 193, in read
    array = self.read_mmap(unpickler)
  File "/home/.local/lib/python3.5/site-packages/joblib/numpy_pickle.py", line 171, in read_mmap
    offset=offset)
  File "/home/.local/lib/python3.5/site-packages/joblib/backports.py", line 23, in make_memmap
    shape=shape, order=order)
  File "/home/.local/lib/python3.5/site-packages/numpy/core/memmap.py", line 264, in __new__
    mm = mmap.mmap(fid.fileno(), bytes, access=acc, offset=start)
ValueError: mmap length is greater than file size
```

**Comment by ikuyamada** [comment]
You need to uncompress the pretrained file before using it.
