### ISSUE TITLE
IndexError when training

### ISSUE THREAD

**Issue by pazzo83** [wikipedia2vec/wikipedia2vec#30]
Hi, we are attempting to run wikipedia2vec on the 20190101 wikidata dump with the following options:
```
wikipedia2vec train --min-link-prob=0.0 --min-prior-prob=0.0 --min-entity-count=0 --dim-size=300 --iteration=10 --negative=15 dumps/enwiki-20190101-pages-articles.xml.bz2 trained/enwiki_20190101_300d.pkl
```
We get through 16.1 million pages processed.  Then there is no log output for several hours until the process dies with the following exception:
```
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/bin/wikipedia2vec", line 11, in <module>
    sys.exit(cli())
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/wikipedia2vec/cli.py", line 52, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/wikipedia2vec/cli.py", line 68, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/wikipedia2vec/cli.py", line 97, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/wikipedia2vec/cli.py", line 34, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/wikipedia2vec/cli.py", line 130, in train
    invoke(build_dump_db, out_file=dump_db_file)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/wikipedia2vec/cli.py", line 126, in invoke
    ctx.invoke(cmd, **cmd_kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/wikipedia2vec/cli.py", line 34, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/wikipedia2vec/cli.py", line 168, in build_dump_db
    DumpDB.build(dump_reader, out_file, **kwargs)
  File "wikipedia2vec/dump_db.pyx", line 156, in wikipedia2vec.dump_db.DumpDB.build
  File "wikipedia2vec/dump_db.pyx", line 182, in wikipedia2vec.dump_db.DumpDB.build
  File "wikipedia2vec/dump_db.pyx", line 186, in wikipedia2vec.dump_db.DumpDB.build
  File "/home/ubuntu/anaconda3/lib/python3.7/multiprocessing/pool.py", line 354, in <genexpr>
    return (item for chunk in result for item in chunk)
  File "/home/ubuntu/anaconda3/lib/python3.7/multiprocessing/pool.py", line 748, in next
    raise value
IndexError: string index out of range
```
This is running on ubuntu 18.04.

**Comment by ikuyamada** [comment]
This problem may be caused by the packages which Wikipedia2Vec depends on.
So, please paste the output of `pip freeze` here.

Also, would you try running this command again with the packages with versions specified in the [requirements.txt](https://github.com/wikipedia2vec/wikipedia2vec/blob/master/requirements.txt) file?
The installation can be done by running `pip install -r requirements.txt`

**Comment by pazzo83** [comment]
Here is the pip freeze of the environment in which I'm running wikipedia2vec:
```
certifi==2019.3.9
click==6.7
Cython==0.28.5
jieba==0.39
joblib==0.11
lmdb==0.94
marisa-trie==0.7.4
mkl-fft==1.0.6
mkl-random==1.0.1
mwparserfromhell==0.5.1
numpy==1.14.2
scipy==1.0.0
six==1.11.0
tqdm==4.19.8
wikipedia2vec==1.0.3
```

Also - this is using python 3.6 - is that supported?

**Comment by pazzo83** [comment]
We were able to build embeddings successfully using the 20180420 wikidata dump - so I don't believe this is an issue with our env.  At least with the 20190101, perhaps there is an issue with that dump where the parsing fails?  It's tough to know what is exactly causing the exception because the stacktrace gets muddled due to multiprocessing.

**Comment by ikuyamada** [comment]
Thank you for your reply!
I suspect that the problem is caused in parsing Wikipedia pages using the mwparserfromhell library.
I am going to spare time soon to reproduce this issue.
BTW, I could successfully build the DumpDB using the December 2018 dump.

**Comment by ikuyamada** [comment]
I reproduced the `IndexError` using the 20190101 dump.
However, I could successfully build the DB using the latest (20190320) dump.
I think the 20190101 dump contains some illegal Wiki markups which cause the IndexError.
Is it possible to use the latest dump instead?

**Comment by pazzo83** [comment]
We were able to successfully build embeddings with the latest dump - so yeah it must've been some issue with the 20190101 version in particular.  Going to close this ticket - thank you for your prompt responses!!
