### ISSUE TITLE
Wikipedia2Vec.load() KeyError

### ISSUE THREAD

**Issue by nihaldsouza** [wikipedia2vec/wikipedia2vec#64]
I have extracted the file and used the binary format of the pretrained model. I have also tried updating the joblib version to 1.0.0 

```python
>>> from wikipedia2vec import Wikipedia2Vec
>>> wiki2vec = Wikipedia2Vec.load("input/enwiki-latest-pages-articles.xml")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "wikipedia2vec/wikipedia2vec.pyx", line 172, in wikipedia2vec.wikipedia2vec.Wikipedia2Vec.load
  File "/Users/nidsouza/anaconda2/envs/streamlit/lib/python3.7/site-packages/joblib/numpy_pickle.py", line 585, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/Users/nidsouza/anaconda2/envs/streamlit/lib/python3.7/site-packages/joblib/numpy_pickle.py", line 504, in _unpickle
    obj = unpickler.load()
  File "/Users/nidsouza/anaconda2/envs/streamlit/lib/python3.7/pickle.py", line 1088, in load
    dispatch[key[0]](self)
KeyError: 60
```

**Comment by ikuyamada** [comment]
Hi,
Thank you for creating the issue.

It looks like you input XML file (input/enwiki-latest-pages-articles.xml) to `Wikipedia2Vec.load` function. Do you input the pretrained model available [here](https://wikipedia2vec.github.io/wikipedia2vec/pretrained/) to the function?

**Comment by nihaldsouza** [comment]
I downloaded it from https://dumps.wikimedia.org/enwiki/latest/enwiki-latest-pages-articles.xml.bz2

**Comment by ikuyamada** [comment]
This is a Wikipedia dump. You need to use pretrained embedding file available here:
https://wikipedia2vec.github.io/wikipedia2vec/pretrained/

**Comment by nihaldsouza** [comment]
Thank you, that worked!
