### ISSUE TITLE
lmdb.Error: mdb_txn_commit: Input/output error when trying to train on dump file.

### ISSUE THREAD

**Issue by lucidviews** [wikipedia2vec/wikipedia2vec#74]
Hi,

First of all, thanks for this great resource! It's exactly what I need for my research project (-:

I'm executing `wikipedia2vec train enwiki-latest-pages-articles.xml.bz2 /home/lucas/luke_data/w2vec` and after processing 11,300,000 pages the process always aborts with the following error:
`Traceback (most recent call last):
  File "/home/lucas/venv/bin/wikipedia2vec", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/lucas/venv/lib/python3.8/site-packages/wikipedia2vec/cli.py", line 52, in wrapper
    return func(*args, **kwargs)
  File "/home/lucas/venv/lib/python3.8/site-packages/wikipedia2vec/cli.py", line 68, in wrapper
    return func(*args, **kwargs)
  File "/home/lucas/venv/lib/python3.8/site-packages/wikipedia2vec/cli.py", line 97, in wrapper
    return func(*args, **kwargs)
  File "/home/lucas/venv/lib/python3.8/site-packages/wikipedia2vec/cli.py", line 34, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/lucas/venv/lib/python3.8/site-packages/wikipedia2vec/cli.py", line 130, in train
    invoke(build_dump_db, out_file=dump_db_file)
  File "/home/lucas/venv/lib/python3.8/site-packages/wikipedia2vec/cli.py", line 126, in invoke
    ctx.invoke(cmd, **cmd_kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/lucas/venv/lib/python3.8/site-packages/wikipedia2vec/cli.py", line 34, in wrapper
    return func(*args, **kwargs)
  File "/home/lucas/venv/lib/python3.8/site-packages/wikipedia2vec/cli.py", line 168, in build_dump_db
    DumpDB.build(dump_reader, out_file, **kwargs)
  File "wikipedia2vec/dump_db.pyx", line 156, in wikipedia2vec.dump_db.DumpDB.build
  File "wikipedia2vec/dump_db.pyx", line 182, in wikipedia2vec.dump_db.DumpDB.build
  File "wikipedia2vec/dump_db.pyx", line 194, in wikipedia2vec.dump_db.DumpDB.build
  File "wikipedia2vec/dump_db.pyx", line 173, in wikipedia2vec.dump_db.DumpDB.build.write_db
lmdb.Error: mdb_txn_commit: Input/output error`.\
\
I'm working on a Ubuntu 20.04.4 LTS sever with 1.5 TB CPU and 32 GB GPU but I only have around 15 GB disk space left.
Since my trial run with a smaller wikipedia dump file on my local machine was successful, I was wondering whether it could be due to the limited disk space. The error message, however, doesn't seem to relate to such a problem from what I understood.\
\
Ultimately I only need the database that contains the mappings of entity names (mentions) and their possible referent entities for my research project so if there is a way to obtain that directly for the entire wikipedia corpus this would also help.\
\
Thanks in advance for your help!

**Comment by ikuyamada** [comment]
@lucidviews Thank you for using Wikipedia2Vec.
The error is raised by the lmdb library and I think it is due to the shortage of the disk space. Unfortunately, you cannot extract the mention-entity mappings without building the database.

**Comment by lucidviews** [comment]
Thank you for your swift response @ikuyamada!
I'll request an increase in disk space and get back to you if it doesn't solve the issue.

**Comment by lucidviews** [comment]
Hello @ikuyamada (-:

After increasing the disk space everything worked as expected but now I am struggling to understand how to use the returned mention.pkl file... After unpickling I don't know how to further process the bytes objects that are contained in the dictionary. Any advice?

Thanks in advance!
